export const GET_SAVED_FILTERS_REQUEST = 'GET_SAVED_FILTERS_REQUEST'
export const GET_SAVED_FILTERS_FAILURE = 'GET_SAVED_FILTERS_FAILURE'
export const GET_SAVED_FILTERS_SUCCESS = 'GET_SAVED_FILTERS_SUCCESS'
